apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: hello-go
  name: hello-go
  namespace: hello-go
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      role: hello-go
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: hello-go
    spec:
      containers:
      - image: __CI_REGISTRY_IMAGE__:__VERSION__
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        name: hello-go 
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
