piVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-go
  namespace: hello-go
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: hello-go.hello-go.svc.cluster.local
spec:
  rules:
    - host: hello-go.{{base_domain}}
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-go
              servicePort: 8080
    tls:
      - secretName: hello-go-tls
        hosts:
          - hello-go.{{base_domain}}
