apiVersion: v1
kind: Service
metadata:
  labels:
    role: hello-go
  name: hello-go
  namespace: hello-go
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    role: hello-go
  type: ClusterIP
